// data.js
export const data = {
    "Afghanistan": { /* details omitted for brevity */ },
    "Albania": { /* details omitted for brevity */ },
    "Algeria": { /* details omitted for brevity */ },
    "Andorra": { /* details omitted for brevity */ },
    "Angola": { /* details omitted for brevity */ },
    "Antigua and Barbuda": { /* details omitted for brevity */ },
    "Argentina": { /* details omitted for brevity */ },
    "Armenia": { /* details omitted for brevity */ },
    "Australia": { /* details omitted for brevity */ },
    "Austria": { /* details omitted for brevity */ },
    "Azerbaijan": { /* details omitted for brevity */ },
    "Bahamas": { /* details omitted for brevity */ },
    "Bahrain": { /* details omitted for brevity */ },
    "Bangladesh": { /* details omitted for brevity */ },
    "Barbados": { /* details omitted for brevity */ },
    "Belarus": { /* details omitted for brevity */ },
    "Belgium": { /* details omitted for brevity */ },
    "Belize": { /* details omitted for brevity */ },
    "Benin": { /* details omitted for brevity */ },
    "Bhutan": { /* details omitted for brevity */ },
    "Bolivia": { /* details omitted for brevity */ },
    "Bosnia and Herzegovina": { /* details omitted for brevity */ },
    "Botswana": { /* details omitted for brevity */ },
    "Brazil": { /* details omitted for brevity */ },
    "Brunei": { /* details omitted for brevity */ },
    "Bulgaria": { /* details omitted for brevity */ },
    "Burkina Faso": { /* details omitted for brevity */ },
    "Burundi": { /* details omitted for brevity */ },
    "Cabo Verde": { /* details omitted for brevity */ },
    "Cambodia": { /* details omitted for brevity */ },
    "Cameroon": { /* details omitted for brevity */ },
    "Canada": { /* details omitted for brevity */ },
    "Central African Republic": { /* details omitted for brevity */ },
    "Chad": { /* details omitted for brevity */ },
    "Chile": { /* details omitted for brevity */ },
    "China": { /* details omitted for brevity */ },
    "Colombia": { /* details omitted for brevity */ },
    "Comoros": { /* details omitted for brevity */ },
    "Congo, Democratic Republic of the": { /* details omitted for brevity */ },
    "Congo, Republic of the": { /* details omitted for brevity */ },
    "Costa Rica": { /* details omitted for brevity */ },
    "Croatia": { /* details omitted for brevity */ },
    "Cuba": { /* details omitted for brevity */ },
    "Cyprus": { /* details omitted for brevity */ },
    "Czech Republic": { /* details omitted for brevity */ },
    "Denmark": { /* details omitted for brevity */ },
    "Djibouti": { /* details omitted for brevity */ },
    "Dominica": { /* details omitted for brevity */ },
    "Dominican Republic": { /* details omitted for brevity */ },
    "East Timor": { /* details omitted for brevity */ },
    "Ecuador": { /* details omitted for brevity */ },
    "Egypt": { /* details omitted for brevity */ },
    "El Salvador": { /* details omitted for brevity */ },
    "Equatorial Guinea": { /* details omitted for brevity */ },
    "Eritrea": { /* details omitted for brevity */ },
    "Estonia": { /* details omitted for brevity */ },
    "Eswatini": { /* details omitted for brevity */ },
    "Ethiopia": { /* details omitted for brevity */ },
    "Fiji": { /* details omitted for brevity */ },
    "Finland": { /* details omitted for brevity */ },
    "France": { /* details omitted for brevity */ },
    "Gabon": { /* details omitted for brevity */ },
    "Gambia": { /* details omitted for brevity */ },
    "Georgia": { /* details omitted for brevity */ },
    "Germany": { /* details omitted for brevity */ },
    "Ghana": { /* details omitted for brevity */ },
    "Greece": { /* details omitted for brevity */ },
    "Grenada": { /* details omitted for brevity */ },
    "Guatemala": { /* details omitted for brevity */ },
    "Guinea": { /* details omitted for brevity */ },
    "Guinea-Bissau": { /* details omitted for brevity */ },
    "Guyana": { /* details omitted for brevity */ },
    "Haiti": { /* details omitted for brevity */ },
    "Honduras": { /* details omitted for brevity */ },
    "Hungary": { /* details omitted for brevity */ },
    "Iceland": { /* details omitted for brevity */ },
    "India": { /* details omitted for brevity */ },
    "Indonesia": { /* details omitted for brevity */ },
    "Iran": { /* details omitted for brevity */ },
    "Iraq": { /* details omitted for brevity */ },
    "Ireland": { /* details omitted for brevity */ },
    "Israel": { /* details omitted for brevity */ },
    "Italy": { /* details omitted for brevity */ },
    "Jamaica": { /* details omitted for brevity */ },
    "Japan": { /* details omitted for brevity */ },
    "Jordan": { /* details omitted for brevity */ },
    "Kazakhstan": { /* details omitted for brevity */ },
    "Kenya": { /* details omitted for brevity */ },
    "Kiribati": { /* details omitted for brevity */ },
    "Kuwait": { /* details omitted for brevity */ },
    "Kyrgyzstan": { /* details omitted for brevity */ },
    "Laos": { /* details omitted for brevity */ },
    "Latvia": { /* details omitted for brevity */ },
    "Lebanon": { /* details omitted for brevity */ },
    "Lesotho": { /* details omitted for brevity */ },
    "Liberia": { /* details omitted for brevity */ },
    "Libya": { /* details omitted for brevity */ },
    "Liechtenstein": { /* details omitted for brevity */ },
    "Lithuania": { /* details omitted for brevity */ },
    "Luxembourg": { /* details omitted for brevity */ },
    "Madagascar": { /* details omitted for brevity */ },
    "Malawi": { /* details omitted for brevity */ },
    "Malaysia": { /* details omitted for brevity */ },
    "Maldives": { /* details omitted for brevity */ },
    "Mali": { /* details omitted for brevity */ },
    "Malta": { /* details omitted for brevity */ },
    "Marshall Islands": { /* details omitted for brevity */ },
    "Mauritania": { /* details omitted for brevity */ },
    "Mauritius": { /* details omitted for brevity */ },
    "Mexico": { /* details omitted for brevity */ },
    "Micronesia": { /* details omitted for brevity */ },
    "Moldova": { /* details omitted for brevity */ },
    "Monaco": { /* details omitted for brevity */ },
    "Mongolia": { /* details omitted for brevity */ },
    "Montenegro": { /* details omitted for brevity */ },
    "Morocco": { /* details omitted for brevity */ },
    "Mozambique": { /* details omitted for brevity */ },
    "Myanmar": { /* details omitted for brevity */ },
    "Namibia": { /* details omitted for brevity */ },
    "Nauru": { /* details omitted for brevity */ },
    "Nepal": { /* details omitted for brevity */ },
    "Netherlands": { /* details omitted for brevity */ },
    "New Zealand": { /* details omitted for brevity */ },
    "Nicaragua": { /* details omitted for brevity */ },
    "Niger": { /* details omitted for brevity */ },
    "Nigeria": { /* details omitted for brevity */ },
    "North Korea": { /* details omitted for brevity */ },
    "North Macedonia": { /* details omitted for brevity */ },
    "Norway": { /* details omitted for brevity */ },
    "Oman": { /* details omitted for brevity */ },
    "Pakistan": { /* details omitted for brevity */ },
    "Palau": { /* details omitted for brevity */ },
    "Panama": { /* details omitted for brevity */ },
    "Papua New Guinea": { /* details omitted for brevity */ },
    "Paraguay": { /* details omitted for brevity */ },
    "Peru": { /* details omitted for brevity */ },
    "Philippines": { /* details omitted for brevity */ },
    "Poland": { /* details omitted for brevity */ },
    "Portugal": { /* details omitted for brevity */ },
    "Qatar": { /* details omitted for brevity */ },
    "Romania": { /* details omitted for brevity */ },
    "Russia": { /* details omitted for brevity */ },
    "Rwanda": { /* details omitted for brevity */ },
    "Saint Kitts and Nevis": { /* details omitted for brevity */ },
    "Saint Lucia": { /* details omitted for brevity */ },
    "Saint Vincent and the Grenadines": { /* details omitted for brevity */ },
    "Samoa": { /* details omitted for brevity */ },
    "San Marino": { /* details omitted for brevity */ },
    "Sao Tome and Principe": { /* details omitted for brevity */ },
    "Saudi Arabia": { /* details omitted for brevity */ },
    "Senegal": { /* details omitted for brevity */ },
    "Serbia": { /* details omitted for brevity */ },
    "Seychelles": { /* details omitted for brevity */ },
    "Sierra Leone": { /* details omitted for brevity */ },
    "Singapore": { /* details omitted for brevity */ },
    "Slovakia": { /* details omitted for brevity */ },
    "Slovenia": { /* details omitted for brevity */ },
    "Solomon Islands": { /* details omitted for brevity */ },
    "Somalia": { /* details omitted for brevity */ },
    "South Africa": { /* details omitted for brevity */ },
    "South Sudan": { /* details omitted for brevity */ },
    "Spain": { /* details omitted for brevity */ },
    "Sri Lanka": { /* details omitted for brevity */ },
    "Sudan": { /* details omitted for brevity */ },
    "Suriname": { /* details omitted for brevity */ },
    "Sweden": { /* details omitted for brevity */ },
    "Switzerland": { /* details omitted for brevity */ },
    "Syria": { /* details omitted for brevity */ },
    "Taiwan": { /* details omitted for brevity */ },
    "Tajikistan": { /* details omitted for brevity */ },
    "Tanzania": { /* details omitted for brevity */ },
    "Thailand": { /* details omitted for brevity */ },
    "Timor-Leste": { /* details omitted for brevity */ },
    "Turkey": { /* details omitted for brevity */ },
    "Turkmenistan": { /* details omitted for brevity */ },
    "Tuvalu": { /* details omitted for brevity */ },
    "Uganda": { /* details omitted for brevity */ },
    "Ukraine": { /* details omitted for brevity */ },
    "United Arab Emirates": { /* details omitted for brevity */ },
    "United Kingdom": { /* details omitted for brevity */ },
    "United States": { /* details omitted for brevity */ },
    "Uruguay": { /* details omitted for brevity */ },
    "Uzbekistan": { /* details omitted for brevity */ },
    "Vanuatu": { /* details omitted for brevity */ },
    "Vatican City": { /* details omitted for brevity */ },
    "Venezuela": { /* details omitted for brevity */ },
    "Vietnam": { /* details omitted for brevity */ },
    "Yemen": { /* details omitted for brevity */ }
};
